/**
 * Shared SEO helpers used by both the live BlogPostPage (real output)
 * and BlogPostForm's read-only schema preview (so the admin sees
 * exactly what will render, generated by the same function).
 */

/** "index,follow" style robots directive from the post's two toggles. */
export function buildRobotsContent(post) {
  const index = post.robotsIndex === false ? 'noindex' : 'index';
  const follow = post.robotsFollow === false ? 'nofollow' : 'follow';
  return `${index},${follow}`;
}

/** JSON-LD BlogPosting schema for a post. Author/category are resolved names, not ids. */
export function buildBlogPostingSchema(post, { authorName, categoryLabel, url } = {}) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: post.seoTitle || post.title,
    description: post.metaDescription || post.excerpt,
    image: post.ogImage || post.featuredImage,
    ...(url ? { mainEntityOfPage: url } : {}),
    ...(categoryLabel ? { articleSection: categoryLabel } : {}),
    datePublished: post.publishedAt || post.createdAt,
    dateModified: post.updatedAt || post.publishedAt || post.createdAt,
    author: { '@type': 'Person', name: authorName || 'HStock Team' },
  };
}
